#!/usr/bin/env python3
"""
Agent Execution Runner — called by Hermes cron to execute queued agent requests.
Reads from D:/QubNexa/hermes/cron/agent-queue/, executes agents via Solar Pro4,
saves results to Obsidian and the queue.
"""

import json
import os
import subprocess
import sys
import time
from pathlib import Path

# Paths — use HERMES_HOME env var if set, else default
HERMES_HOME = Path(os.environ.get("HERMES_HOME", "D:/QubNexa/hermes")).resolve()
HERMES_BIN = HERMES_HOME / "bin" / "hermes.exe"
QUEUE_DIR = HERMES_HOME / "cron" / "agent-queue"
# Resolve: D:\QubNexa\hermes -> drive D:\ -> Obsidian Vault\...
AGENTS_DIR = Path(HERMES_HOME.drive + "\\") / "Obsidian Vault" / "Projects" / "QubNexa" / "agency-agents"
OUTPUT_DIR = Path("D:/Obsidian Vault/Projects/QubNexa/Agents/Executions")
MODEL = "upstage/solar-pro4:free"

def load_agent_prompt(agent_filename: str) -> str | None:
    """Load the full markdown content of an agent file."""
    # Try direct path
    agent_path = AGENTS_DIR / agent_filename
    if agent_path.exists():
        with open(agent_path) as f:
            return f.read()
    # Try subdirectories
    for subdir in AGENTS_DIR.iterdir():
        if subdir.is_dir():
            candidate = subdir / agent_filename
            if candidate.exists():
                with open(candidate) as f:
                    return f.read()
    return None

def strip_frontmatter(content: str) -> str:
    """Remove YAML frontmatter from agent markdown."""
    parts = content.split("---", 2)
    if len(parts) >= 3:
        return parts[2].strip()
    return content.strip()

def call_solar_pro4(system_prompt: str, user_prompt: str) -> str:
    """
    Call Solar Pro4 via Hermes CLI oneshot mode.
    Hermes.exe --oneshot sends a single prompt through the configured provider
    (Nous Portal with auth) and returns only the model's text response.
    """
    # Build the full prompt: system context + user task
    full_prompt = (
        f"<SYSTEM>\n{system_prompt}\n</SYSTEM>\n\n"
        f"<USER_TASK>\n{user_prompt}\n</USER_TASK>\n\n"
        "Provide your complete response as the agent persona described above. "
        "Do not explain that you are an AI — respond as the agent."
    )

    env = os.environ.copy()
    env["HERMES_HOME"] = str(HERMES_HOME)

    try:
        result = subprocess.run(
            [str(HERMES_BIN), "--oneshot", full_prompt, "-m", MODEL],
            capture_output=True,
            text=True,
            timeout=300,  # 5 minutes max per execution
            env=env,
            cwd=str(HERMES_HOME),
        )

        output = result.stdout.strip()
        if result.returncode != 0 and not output:
            error_text = result.stderr.strip()
            return f"[EXECUTION ERROR]\nReturn code: {result.returncode}\nError: {error_text[:500]}"
        return output if output else "[EMPTY RESPONSE]"

    except subprocess.TimeoutExpired:
        return "[EXECUTION TIMEOUT]\nThe agent execution exceeded 5 minutes and was terminated."
    except FileNotFoundError:
        return f"[EXECUTION ERROR]\nHermes binary not found at: {HERMES_BIN}"
    except Exception as e:
        return f"[EXECUTION ERROR]\nUnexpected: {type(e).__name__}: {str(e)[:500]}"

def save_result_to_obsidian(execution_id: str, agent_name: str, result: str):
    """Save agent execution result to Obsidian."""
    output_dir = OUTPUT_DIR
    output_dir.mkdir(parents=True, exist_ok=True)
    
    # Strip .md from agent name if present, then add .md extension
    clean_name = agent_name.replace('.md', '') if agent_name.endswith('.md') else agent_name
    filename = f"{execution_id}-{clean_name.replace(' ', '-')}.md"
    filepath = output_dir / filename
    
    content = f"""---
type: agent-execution
agent: {agent_name}
execution_id: {execution_id}
created: {time.strftime('%Y-%m-%d %H:%M:%S')}
---

# Agent Execution: {agent_name}

## Task
Pending review

## Result
{result}

---
*Generated by QubNexa AI Agency — {time.strftime('%Y-%m-%d')}*
"""
    with open(filepath, "w") as f:
        f.write(content)
    
    return str(filepath)

def process_queue():
    """Process all queued agent execution requests."""
    if not QUEUE_DIR.exists():
        print("Queue directory not found:", QUEUE_DIR)
        return

    queue_files = list(QUEUE_DIR.glob("*.json"))
    queue_files = [f for f in queue_files if not f.name.startswith("_")]

    if not queue_files:
        print("No queued executions found.")
        return

    print(f"Found {len(queue_files)} queued executions")

    for queue_file in queue_files:
        try:
            with open(queue_file) as f:
                execution = json.load(f)

            print(f"\nProcessing: {execution['id']}")
            print(f"  Agent: {execution['agent']}")
            print(f"  Task: {execution['task'][:80]}...")

            # Load agent prompt
            agent_filename = execution['agent']
            if execution.get('agent_filepath'):
                agent_filename = execution['agent_filepath']

            prompt_content = load_agent_prompt(agent_filename)
            if not prompt_content:
                print(f"  ERROR: Agent file not found: {agent_filename}")
                execution['status'] = 'error'
                execution['error'] = f'Agent file not found: {agent_filename}'
                execution['updated_at'] = time.strftime('%Y-%m-%d %H:%M:%S')
                with open(queue_file, 'w') as f:
                    json.dump(execution, f, indent=2)
                continue

            system_prompt = strip_frontmatter(prompt_content)
            user_prompt = execution['task']

            print(f"  System prompt: {len(system_prompt)} chars")

            # Execute (placeholder — real implementation uses Hermes CLI)
            result = call_solar_pro4(system_prompt, user_prompt)

            print(f"  Result: {len(result)} chars")

            # Save result
            execution['status'] = 'completed'
            execution['result'] = result
            execution['result_path'] = save_result_to_obsidian(
                execution['id'], execution['agent'], result
            )
            execution['completed_at'] = time.strftime('%Y-%m-%d %H:%M:%S')
            execution['updated_at'] = execution['completed_at']

            with open(queue_file, 'w') as f:
                json.dump(execution, f, indent=2)

            print(f"  Saved to: {execution['result_path']}")

        except Exception as e:
            print(f"  ERROR processing {queue_file.name}: {e}")
            try:
                with open(queue_file) as f:
                    execution = json.load(f)
                execution['status'] = 'error'
                execution['error'] = str(e)
                execution['updated_at'] = time.strftime('%Y-%m-%d %H:%M:%S')
                with open(queue_file, 'w') as f:
                    json.dump(execution, f, indent=2)
            except:
                pass

    print("\nDone processing queue.")

if __name__ == "__main__":
    process_queue()