import { getLatestReport } from "@/lib/db/queries";

export const metadata = {
  title: "Morning Report — QubNexa Dashboard",
  description: "Latest orchestrator morning report.",
};

export default function ReportPage() {
  const report = getLatestReport();

  return (
    <div className="flex min-h-screen flex-col bg-[var(--bg)] text-[var(--ink)]">
      <header className="sticky top-0 z-30 border-b border-[var(--ink-10)] bg-[var(--bg)]/80 backdrop-blur-md">
        <div className="container-x flex h-14 items-center justify-between px-3 py-2 md:px-4">
          <div className="flex items-center gap-3">
            <span className="label-mono text-[var(--accent-strong)]">QubNexa</span>
            <span className="hidden sm:inline text-sm text-[var(--ink-50)]">/ Morning Report</span>
          </div>
          <a
            href="/dashboard"
            className="glass-pill text-xs"
          >
            Back to dashboard
          </a>
        </div>
      </header>

      <main className="container-x flex-1 px-1.5 pb-10 pt-6 md:px-2.5 md:pt-8">
        {report ? (
          <article className="max-w-3xl rounded-2xl border border-[var(--ink-10)] bg-[var(--bg-raised)] p-6 md:p-8 shadow-sm">
            <div className="mb-6 flex items-center justify-between">
              <div>
                <h1 className="text-display-lg font-semibold tracking-tight text-[var(--ink)]">
                  Morning Report
                </h1>
                <p className="mt-1 text-sm text-[var(--ink-50)]">
                  {new Date(report.date).toLocaleDateString("en-US", {
                    weekday: "long",
                    year: "numeric",
                    month: "long",
                    day: "numeric",
                  })}
                  {" · "}
                  Generated {new Date(report.created_at).toLocaleString("en-US", {
                    hour: "2-digit",
                    minute: "2-digit",
                  })}
                </p>
              </div>
              <span className="label-mono text-xs text-[var(--accent-strong)]">ORCHESTRATOR</span>
            </div>

            <div className="rounded-xl border border-[var(--ink-10)] bg-[var(--bg)]/50 p-5 text-sm leading-relaxed whitespace-pre-wrap font-mono text-[var(--ink-70)]">
              {report.summary}
            </div>

            <div className="mt-6 flex items-center gap-3 rounded-xl border border-[var(--sand-tint)] bg-[var(--sand-tint)] p-4 text-sm">
              <svg className="h-5 w-5 shrink-0 text-[var(--sand-deep)]" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
                <path d="M12 2a10 10 0 1 0 10 10A10 10 0 0 0 12 2Zm0 18a8 8 0 1 1 8-8 8 8 0 0 1-8 8Z" />
                <path d="M12 8v4M12 16h.01" />
              </svg>
              <div>
                <p className="font-medium text-[var(--ink)]">Needs attention</p>
                <p className="text-xs text-[var(--sand-deep)] mt-0.5">{report.needs_attention}</p>
              </div>
            </div>

            <p className="mt-8 text-xs text-[var(--ink-30)]">
              This report is generated by the orchestrator. Run it manually from the dashboard header,
              or wait for the scheduled morning run.
            </p>
          </article>
        ) : (
          <div className="mx-auto max-w-2xl rounded-2xl border border-[var(--ink-10)] bg-[var(--bg-raised)] p-12 text-center shadow-sm">
            <svg className="mx-auto h-10 w-10 text-[var(--ink-30)]" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">
              <path d="M12 8v4l3 3m6-3a9 9 0 1 1-18 0 9 9 0 0 1 18 0Z" />
            </svg>
            <h2 className="mt-4 text-heading text-lg font-semibold">No report yet</h2>
            <p className="mt-2 text-sm text-[var(--ink-50)]">
              Run the orchestrator from the dashboard to generate the first morning report.
            </p>
            <a
              href="/dashboard"
              className="mt-5 inline-flex rounded-lg bg-[var(--accent)] px-5 py-2.5 text-sm font-medium text-white transition-colors hover:bg-[var(--accent-strong)] focus-visible:outline-2 focus-visible:outline-[var(--accent)]"
            >
              Go to dashboard
            </a>
          </div>
        )}
      </main>
    </div>
  );
}
